/*

    REACH CONSTANTS

*/
const REACH_NETWORK = "TestNet";
const REACH_PROVIDER_ENV = {
    REACH_CONNECTOR_MODE: "ALGO",
    REACH_ISOLATED_NETWORK: "yes",
};

export { REACH_PROVIDER_ENV, REACH_NETWORK };
